Hw1
bifidok/Tinkoff pull request #1
Opened 2023-10-05 23:38 UTC by bifidok

2023-10-06 17:48 UTC, infomouse requested changes

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +    private static int secondsInMinute = 60;
Обычно константы объявляются как static final. Имена констант пишутся в SCREAMING_SNAKE_CASE.
После таких изменений можно будет убрать @SuppressWarnings.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +    private static int counter = 0;
Нельзя использовать переменные уровня класса в расчетах внутри функции. Это приводит к непредсказуемым результатам, если функцию будут вызывать из разных мест.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +        long secs = Long.parseLong(minsAndSecs[1]);
Если в строке будет буква, то здесь получим NumberFormatException. А по условию должны возвращать -1.

Если знакомы с регулярками, то валидацию можно сделать с помощью метода String.matches().

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +    public static boolean isNestable(int[] a1, int[] a2) throws NullPointerException {
RuntimeException не надо декларировать.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +            throw new NullPointerException();
Исключения лучше кидать с понятным описанием.
Например,  throw new NullPointerException("Input array cannot be null");
На мой взгляд тут уместнее кинуть IllegalArgumentException.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +        if (temp < 0) {
Это можно сделать с помощью стандартной функции Math.abs() в момент объявления переменной temp.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +    public static int countDigits(int value) {
Ошибка: countDigits(Integer.MIN_VALUE) возвращает 1.
Всегда надо делать тесты на граничные значения.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +        return mins * secondsInMinute + secs;
При умножении надо помнить о переполнении. minutesToSeconds(Long.MAX_VALUE + ":00") вернет -60.
Всегда надо делать тесты на граничные значения.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +    public static boolean isNestable(int[] a1, int[] a2) throws NullPointerException {
Лучше избегать однобуквенных переменных, array1 и array2 намного лучше в плане читаемости кода.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +        StringBuilder builder = new StringBuilder();
Если мы знаем итоговую длину, то надо сразу указывать ее в конструкторе. Это позволит избежать лишних операций с памятью внутри билдера.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +    public static boolean isPalindromeDescendant(long value) {
Лайфак на будущее. Если в задании явно не указан тип параметра, то используйте int. Это даст возможность внутри метода использовать long для вычислений и не получать переполнения.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +    public static boolean isPalindromeDescendant(long value) {
isPalindromeDescendant(1) возвращает false, хотя это палиндром.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +        while (shiftCounter > 0) {
Можно обойтись без цикла. StringBuilder позволяет вырезать и вставлять кусками.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +        if (chessBoard == null || chessBoard.length != boardSize || chessBoard[0].length != boardSize) {
Проверка chessBoard[0].length != boardSize не гарантирует, что остальные строки в матрице будут такой же длины.
Пример, int[][] board = new int[][] {{1}, {2, 3}, {4, 5, 6}};

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +            throw new AssertionError();
AssertionError тут неуместен. Исключения Error используются в ситуациях, когда приложение в целом не может продолжать работать.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +        int[][] waysToMove = new int[][] {
Утечка памяти. На каждую проверку создается массив, который не изменяется. Надо вынести в константу.

2023-10-06 17:48 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +    private static boolean isInBoundaries(int[][] chessBoard, int x, int y) {
Нет смысла сюда передавать chessBoard. У нас же есть константа размера доски и валидация того, что переданная доска соответствуют ей.

2023-10-07 00:59 UTC, bifidok commented
По каждому пункту исправил

2023-10-09 21:14 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +        if (!value.matches("\\d{1," + INTEGER_MAX_DIGITS + "}:\\d{1," + INTEGER_MAX_DIGITS + "}")) {
Можно секунды сразу ограничить 2 символами.

2023-10-09 21:14 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +    public static String fixString(String broken) {
Просто мысль на будущее. StringBuilder - это хорошо, но всегда оптимально. В данном случае можно сделать массив символов методом String.toCharArray() и делать свапы в нем.

2023-10-09 21:14 UTC, infomouse commented on src/main/java/edu/hw1/Exercises.java
> +    private static int upperBound = 10000;
Не хватает final модификатора.

2023-10-10 09:12 UTC, merged