Hw2
bifidok/Tinkoff pull request #3
Opened 2023-10-15 04:17 UTC by bifidok

Не получилось протестировать 3 задание из-за рандома в выборе типа соединений и менеджера, пробовал подключить мокито - не получилось

2023-10-15 09:18 UTC, infomouse commented on src/main/java/edu/hw2/Task1/Expr.java
> +package edu.hw2.Task1;
Имена пакетов должны быть в нижнем регистре.
https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

2023-10-15 09:18 UTC, infomouse commented on src/test/java/edu/hw2/ExprTest.java
> +package edu.hw2;
Тесты должны лежать в таком же пакете, что и тестируемый класс.

2023-10-15 09:40 UTC, infomouse commented
> Не получилось протестировать 3 задание из-за рандома в выборе типа соединений и менеджера, пробовал подключить мокито - не получилось

Попробуйте вот так:
![image](https://github.com/bifidok/Tinkoff/assets/13957950/faf4d07e-d939-4778-b700-6418bd52ca49)

2023-10-15 09:48 UTC, infomouse commented
> Не получилось протестировать 3 задание из-за рандома в выборе типа соединений и менеджера, пробовал подключить мокито - не получилось

Не силен в junit, потому что пишу тесты на spock. Но вот мой пример теста:
```java
class PopularCommandExecutorTest {
    private static final int MAX_ATTEMPS = 3;

    private ConnectionManager connectionManager = mock(ConnectionManager.class);

    private PopularCommandExecutor executor = new PopularCommandExecutor(connectionManager, MAX_ATTEMPS);

    @Test
    void tryExecute() throws Exception {
        String command = "test";
        Connection connection = mock(Connection.class);
        when(connectionManager.getConnection()).thenReturn(connection);

        executor.tryExecute(command);

        verify(connection, times(1)).execute(command);
        verify(connection, times(1)).close();
    }
}
```

2023-10-15 10:03 UTC, infomouse commented on src/main/java/edu/hw2/Main.java
> +public final class Main {
Зачем этот класс? Надо стараться не коммитить бесполезные классы.

2023-10-15 15:58 UTC, bifidok commented
Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
https://github.com/raphw/byte-buddy/issues/1396
Ошибка из-за мокито появилась, но на 19 jdk тесты проходят

2023-10-15 17:04 UTC, infomouse commented
> Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property [raphw/byte-buddy#1396](https://github.com/raphw/byte-buddy/issues/1396) Ошибка из-за мокито появилась, но на 19 jdk тесты проходят

А фикс из тикета пробовали?
![image](https://github.com/bifidok/Tinkoff/assets/13957950/c80fa795-976c-4b2a-ac9a-ee1ad5487cb4)

2023-10-16 03:05 UTC, bifidok commented
Не знал куда это вводить, спасибо

2023-10-17 09:10 UTC, infomouse requested changes

2023-10-17 09:10 UTC, infomouse commented on src/main/java/edu/hw2/task2/Square.java
> +public class Square extends Rectangle {
LSP нарушен.
```java
    private static boolean isLsp(Rectangle rectangle) {
        return rectangle.setHeight(10).setWidth(20).area() == 200;
    }
```
isLsp(new Square(0)) возвращает false.

2023-10-17 09:10 UTC, infomouse commented on src/main/java/edu/hw2/task2/Rectangle.java
> +    private int width;
Если сеттеры возвращают новый объект, то по сути объект неизменяем и поля надо делать final.

2023-10-17 09:10 UTC, infomouse commented on src/main/java/edu/hw2/task4/Call.java
> +        int stackLength = stackTrace.length;
Неиспользуемый код надо удалять.

2023-10-17 09:10 UTC, infomouse commented on src/main/java/edu/hw2/task3/connection/Connection.java
> +    double PROBABLITY_BOUND = 0.5;
В интерфейсе должен быть только общий контракт для всех реализаций.

2023-10-17 09:10 UTC, infomouse commented on src/main/java/edu/hw2/task3/connection/FaultyConnection.java
> +            throw new ConnectionException("Connection cannot be established", new Exception());
Так неправильно делать. Если нет cause, то надо использовать конструктор без нее. Создавать смысла нет, будет просто дублирование содержимого ConnectionException.

2023-10-17 09:10 UTC, infomouse commented on src/main/java/edu/hw2/task3/connectionmanager/ConnectionManager.java
> +    double PROBABLITY_BOUND = 0.5;
Аналогично Connection.

2023-10-17 09:10 UTC, infomouse commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +                attemps = maxAttemps;
Лучше просто сделать return. Это гораздо понятнее.

2023-10-17 09:10 UTC, infomouse commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +    private void tryExecute(String command) {
Не выполнено требование:
Если tryExecute не смог выполнить команду (превышено количество попыток), то нужно вернуть ConnectionException, при этом сохранив оригинальное исключение в параметре cause

2023-10-18 13:01 UTC, infomouse commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +    private final static Logger LOGGER = LogManager.getLogger();
Обычно константы объявляют вначале класса и отделяют строкой от других полей.

2023-10-18 13:01 UTC, infomouse approved these changes

2023-10-18 13:47 UTC, merged