Project2
bifidok/Tinkoff pull request #7
Opened 2023-10-28 21:27 UTC by bifidok

Алгоритмы решения - bfs, dfs
Алгоритмы генерации - recursive backtracker, hunt and kill, алгоритм Прима.
Алгоритмы генерации не совсем подходят под описание со статьи хабра, т.к. у меня стена - это такая же ячейка, как и проход , но суть та же.
В алгоритмах генерации есть одинаковые приватные методы, не понимаю куда их можно вынести или это нормально.

![rebacktrack](https://github.com/bifidok/Tinkoff/assets/16528008/bd813b40-13a9-4b49-b58a-336d6b4c570a)
![prima](https://github.com/bifidok/Tinkoff/assets/16528008/a04fcc5e-ffc1-4108-9e37-b7b24ebb3aee)
![hunt](https://github.com/bifidok/Tinkoff/assets/16528008/71655923-f9f9-4d1c-afde-fdd53563703c)

2023-10-28 21:53 UTC, bifidok commented
Покрытие тестов почему-то перестало отображаться после фикса этой ошибки
Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property
https://github.com/raphw/byte-buddy/issues/1396

2023-12-07 14:26 UTC, YuriiKondratov requested changes
Привет) Замечания по кодстайлу - чисто тебе для общего развития. Давай исправим последнее замечание (про тесты), и тогда будет полный балл)

2023-12-07 14:26 UTC, YuriiKondratov commented on src/main/java/edu/project2/MazePrinter.java
> +    private final MazeRenderer renderer;
Хотелось бы здесь видеть зависимость от абстракции (буква D из принципов SOLID):
```suggestion
    private final Renderer renderer;
    
    public MazePrinter(Renderer renderer) {
        this.renderer = renderer;
    }
```
для того, чтобы можно было передать сюда любую другую реализацию Renderer (например, если ты захочешь отрисовывать лабиринт в другом стиле).

2023-12-07 14:26 UTC, YuriiKondratov commented on src/main/java/edu/project2/generator/HuntAndKillGenerator.java
> +    private final static int INCORRECT_SIDE_LENGTH = 3;
Я бы поменял название на что-то вроде MIN_SIDE_LENGTH. Мне как читателю было не очевидно что в данном контексте значит "INCORRECT"

2023-12-07 14:26 UTC, YuriiKondratov commented on src/main/java/edu/project2/generator/HuntAndKillGenerator.java
> +    private void generateBox(Cell[][] grid) {
Про вынесение одинаковых методов. Глобально есть два основных способа переиспользования кода: наследование и вынесение в отдельный класс. На тему того, что выбирать, можешь почитать статьи типа "inheritance vs composition".
Но тут я бы создал класс `MazeUtil`  со `static` методами, которые ты хочешь переиспользовать (например `public static void generateBox(...)`. И в методы я бы передавал не grid, а maze, который бы предварительно создавал пустым.
Короче как-то так:
```java
Maze maze = MazeUtil.createEmptyMaze();
MazeUtil.generateIn(maze);
MazeUtil.generateOut(maze);
```
передаем maze, а не grid, чтобы не было выражений типа `grid[i].length - 1`, а было `maze.width`, т.к. первое сложно воспринимается при чтении кода)

2023-12-07 14:26 UTC, YuriiKondratov commented on src/main/java/edu/project2/generator/HuntAndKillGenerator.java
> +        if (x <= 0 || y <= 0 || x >= grid[0].length - 1 || y >= grid.length - 1) {
У тебя в других генераторах есть прекрасный метод `isInBounds` - его использование читается гораздо легче чем огромное условие. Опять же, этот метод можно вынести в `MazeUtil`.

2023-12-07 14:26 UTC, YuriiKondratov commented on src/test/java/edu/project2/solver/BFSSolverTest.java
> +        var answer = solver.solve(maze);
Не злоупотребляй использованием var. Когда я читал эту строку, мне пришлось промотать кучу кода наверх, чтобы понять, какой тип возвращает `solve` - это замедляет процесс ревью.

2023-12-07 14:26 UTC, YuriiKondratov commented on src/test/java/edu/project2/solver/DFSSolverTest.java
> +        assertThat(answer.contains(maze.getStart())).isTrue();
Довольно странные проверки правильности прохождения лабиринта. А что если какой-нибудь неопытный разработчик поломает код, и мы пройдём через точку конца, не заметив, что это конец? Тогда тест не упадет и ошибку мы не заметим, в худшем случае она попадет в прод) 

Хотелось бы увидеть такой тест: делаем `solve` лабиринта и четко проверяем, что правильно нашли конец и начало. Чтобы точно понимать, где конец, а где начало `solve` должен возвращать не `set` а `list`. Тогда первый элемент листа - начало, последний - конец.

Хочу увидеть что-то такое:
```java
        MazeGenerator generator = new HuntAndKillGenerator();
        Maze maze = generator.generate(10, 10);
        MazeSolver solver = new DepthFirstSearchSolver();

        List<Cell> answer = solver.solve(maze);

        assertEquals(maze.getStart(), answer.get(0));
        assertEquals(maze.getEnd(), answer.get(answer.size() - 1));
```

2023-12-07 18:14 UTC, bifidok commented
Привет, спасибо за пояснения) Исправил

2024-01-14 23:08 UTC, merged